# Generated by Django 3.2.4 on 2021-08-18 00:07

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import registers.models
import simple_history.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Users',
            fields=[
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('username', models.CharField(max_length=10, unique=True, verbose_name='Numero de cedula')),
                ('password', models.CharField(max_length=255, verbose_name='Contraseña')),
                ('names', models.CharField(blank=True, max_length=150, null=True, verbose_name='Nombres')),
                ('surnames', models.CharField(blank=True, max_length=150, null=True, verbose_name='Apellidos')),
                ('cycle', models.CharField(choices=[('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5'), ('Egresado', 'Egresado'), ('Docente', 'Docente')], default='available', max_length=200, verbose_name='Ciclo')),
                ('tecnology', models.CharField(choices=[('TECNOLOGIA SUPERIOR EN DESARROLLO DE SOFTWARE', 'TECNOLOGIA SUPERIOR EN DESARROLLO DE SOFTWARE'), ('TECNOLOGIA SUPERIOR EN CONTABILIDAD', 'TECNOLOGIA SUPERIOR EN CONTABILIDAD'), ('Docente', 'Docente')], default='available', max_length=200, verbose_name='Tecnologia')),
                ('image', models.ImageField(blank=True, null=True, upload_to=registers.models.url_user, verbose_name='Imagen')),
                ('user_active', models.BooleanField(default=True, verbose_name='usuario activo')),
                ('user_admin', models.BooleanField(default=False, verbose_name='usuario administrador')),
                ('phone', models.IntegerField(blank=True, null=True, verbose_name='Telefono')),
                ('email', models.EmailField(blank=True, max_length=254, null=True, verbose_name='Correo')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'usuario',
                'verbose_name_plural': 'usuarios',
                'ordering': ['names'],
            },
        ),
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=150, verbose_name='Titulo')),
                ('author', models.CharField(max_length=150, verbose_name='Autor')),
                ('state', models.BooleanField(default=True, verbose_name='Estado')),
                ('image', models.ImageField(blank=True, null=True, upload_to=registers.models.url_book, verbose_name='Imagen')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'libro',
                'verbose_name_plural': 'libros',
                'ordering': ['title'],
            },
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Nombre')),
                ('state', models.BooleanField(default=True, verbose_name='Estado')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'categoria',
                'verbose_name_plural': 'categorias',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Secretary',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('role', models.CharField(default='Secretari@', max_length=100, verbose_name='Rol Desempeñado')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now_add=True)),
                ('name', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'secretaria',
                'verbose_name_plural': 'secretarias',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('state', models.BooleanField(default=True, verbose_name='Estado')),
                ('deliver_date', models.DateTimeField(verbose_name='Fecha de Entrega')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now_add=True)),
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='registers.book')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'pedido',
                'verbose_name_plural': 'pedidos',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Librarian',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('role', models.CharField(default='Bibliotecari@', max_length=100, verbose_name='Rol Desempeñado')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now_add=True)),
                ('name', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'bibliotecario',
                'verbose_name_plural': 'bibliotecarios',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='HistoricalUsers',
            fields=[
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('id', models.IntegerField(blank=True, db_index=True)),
                ('username', models.CharField(db_index=True, max_length=10, verbose_name='Numero de cedula')),
                ('password', models.CharField(max_length=255, verbose_name='Contraseña')),
                ('names', models.CharField(blank=True, max_length=150, null=True, verbose_name='Nombres')),
                ('surnames', models.CharField(blank=True, max_length=150, null=True, verbose_name='Apellidos')),
                ('cycle', models.CharField(choices=[('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5'), ('Egresado', 'Egresado'), ('Docente', 'Docente')], default='available', max_length=200, verbose_name='Ciclo')),
                ('tecnology', models.CharField(choices=[('TECNOLOGIA SUPERIOR EN DESARROLLO DE SOFTWARE', 'TECNOLOGIA SUPERIOR EN DESARROLLO DE SOFTWARE'), ('TECNOLOGIA SUPERIOR EN CONTABILIDAD', 'TECNOLOGIA SUPERIOR EN CONTABILIDAD'), ('Docente', 'Docente')], default='available', max_length=200, verbose_name='Tecnologia')),
                ('image', models.TextField(blank=True, max_length=100, null=True, verbose_name='Imagen')),
                ('user_active', models.BooleanField(default=True, verbose_name='usuario activo')),
                ('user_admin', models.BooleanField(default=False, verbose_name='usuario administrador')),
                ('phone', models.IntegerField(blank=True, null=True, verbose_name='Telefono')),
                ('email', models.EmailField(blank=True, max_length=254, null=True, verbose_name='Correo')),
                ('created', models.DateTimeField(blank=True, editable=False)),
                ('updated', models.DateTimeField(blank=True, editable=False)),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField()),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'historical usuario',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': 'history_date',
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.AddField(
            model_name='book',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='registers.category'),
        ),
    ]
