# Generated by Django 3.2.4 on 2021-06-27 19:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registers', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='book',
            options={'ordering': ['title'], 'verbose_name': 'book', 'verbose_name_plural': 'books'},
        ),
        migrations.AlterModelOptions(
            name='category',
            options={'ordering': ['name'], 'verbose_name': 'category', 'verbose_name_plural': 'categories'},
        ),
        migrations.AlterModelOptions(
            name='order',
            options={'ordering': ['id'], 'verbose_name': 'order', 'verbose_name_plural': 'orders'},
        ),
        migrations.AlterModelOptions(
            name='student',
            options={'ordering': ['names'], 'verbose_name': 'student', 'verbose_name_plural': 'students'},
        ),
        migrations.AddField(
            model_name='student',
            name='tecnology',
            field=models.CharField(choices=[('DS', 'TECNOLOGIA SUPERIOR EN DESARROLLO DE SOFTWARE'), ('CT', 'TECNOLOGIA SUPERIOR EN CONTABILIDAD')], default='available', max_length=100),
        ),
    ]
