# Generated by Django 3.2.4 on 2021-08-04 17:57

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import simple_history.models


class Migration(migrations.Migration):

    dependencies = [
        ('registers', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='book',
            options={'ordering': ['title'], 'verbose_name': 'libro', 'verbose_name_plural': 'libros'},
        ),
        migrations.AlterModelOptions(
            name='category',
            options={'ordering': ['name'], 'verbose_name': 'categoria', 'verbose_name_plural': 'categorias'},
        ),
        migrations.AlterModelOptions(
            name='librarian',
            options={'ordering': ['name'], 'verbose_name': 'bibliotecario', 'verbose_name_plural': 'bibliotecarios'},
        ),
        migrations.AlterModelOptions(
            name='order',
            options={'ordering': ['id'], 'verbose_name': 'pedido', 'verbose_name_plural': 'pedidos'},
        ),
        migrations.AlterModelOptions(
            name='secretary',
            options={'ordering': ['name'], 'verbose_name': 'secretaria', 'verbose_name_plural': 'secretarias'},
        ),
        migrations.CreateModel(
            name='HistoricalUsers',
            fields=[
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('id', models.IntegerField(blank=True, db_index=True)),
                ('username', models.CharField(db_index=True, max_length=10, verbose_name='Numero de cedula')),
                ('names', models.CharField(blank=True, max_length=150, null=True, verbose_name='Nombres')),
                ('surnames', models.CharField(max_length=150, verbose_name='Apellidos')),
                ('cycle', models.CharField(choices=[('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5'), ('Egresado', 'Egresado'), ('Docente', 'Docente')], default='available', max_length=100, verbose_name='Ciclo')),
                ('tecnology', models.CharField(choices=[('TECNOLOGIA SUPERIOR EN DESARROLLO DE SOFTWARE', 'TECNOLOGIA SUPERIOR EN DESARROLLO DE SOFTWARE'), ('TECNOLOGIA SUPERIOR EN CONTABILIDAD', 'TECNOLOGIA SUPERIOR EN CONTABILIDAD'), ('Docente', 'Docente')], default='available', max_length=100, verbose_name='Tecnologia')),
                ('image', models.TextField(max_length=100, verbose_name='Imagen')),
                ('user_active', models.BooleanField(default=True)),
                ('user_admin', models.BooleanField(default=False)),
                ('phone', models.IntegerField(blank=True, null=True, verbose_name='Telefono')),
                ('email', models.EmailField(max_length=254, verbose_name='Correo')),
                ('created', models.DateTimeField(blank=True, editable=False)),
                ('updated', models.DateTimeField(blank=True, editable=False)),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField()),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'historical usuario',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': 'history_date',
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
    ]
