# Generated by Django 3.2.4 on 2021-08-18 03:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('registers', '0002_auto_20210817_2120'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='historicalusers',
            name='is_superuser',
        ),
        migrations.RemoveField(
            model_name='users',
            name='groups',
        ),
        migrations.RemoveField(
            model_name='users',
            name='is_superuser',
        ),
        migrations.RemoveField(
            model_name='users',
            name='user_permissions',
        ),
    ]
