# Generated by Django 3.2.4 on 2021-08-04 18:10

from django.db import migrations, models
import registers.models


class Migration(migrations.Migration):

    dependencies = [
        ('registers', '0002_auto_20210804_1257'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='author',
            field=models.CharField(max_length=150, verbose_name='Autor'),
        ),
        migrations.AlterField(
            model_name='book',
            name='image',
            field=models.ImageField(upload_to=registers.models.url_book, verbose_name='Imagen'),
        ),
        migrations.AlterField(
            model_name='book',
            name='state',
            field=models.BooleanField(default=True, verbose_name='Estado'),
        ),
        migrations.AlterField(
            model_name='book',
            name='title',
            field=models.CharField(max_length=150, verbose_name='Titulo'),
        ),
        migrations.AlterField(
            model_name='category',
            name='name',
            field=models.CharField(max_length=100, verbose_name='Nombre'),
        ),
        migrations.AlterField(
            model_name='category',
            name='state',
            field=models.BooleanField(default=True, verbose_name='Estado'),
        ),
        migrations.AlterField(
            model_name='librarian',
            name='role',
            field=models.CharField(default='Bibliotecari@', max_length=100, verbose_name='Rol Desempeñado'),
        ),
        migrations.AlterField(
            model_name='order',
            name='deliver_date',
            field=models.DateField(verbose_name='Fecha de Entrega'),
        ),
        migrations.AlterField(
            model_name='order',
            name='state',
            field=models.BooleanField(default=True, verbose_name='Estado'),
        ),
        migrations.AlterField(
            model_name='secretary',
            name='role',
            field=models.CharField(default='Secretari@', max_length=100, verbose_name='Rol Desempeñado'),
        ),
    ]
