# Generated by Django 3.2.4 on 2021-08-07 03:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registers', '0003_auto_20210804_1310'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicalusers',
            name='phone',
            field=models.IntegerField(blank=True, max_length=10, null=True, verbose_name='Telefono'),
        ),
        migrations.AlterField(
            model_name='users',
            name='phone',
            field=models.IntegerField(blank=True, max_length=10, null=True, verbose_name='Telefono'),
        ),
    ]
