# Generated by Django 3.2.4 on 2021-09-10 01:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registers', '0003_auto_20210817_2212'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicalusers',
            name='email',
            field=models.EmailField(blank=True, db_index=True, max_length=254, null=True, verbose_name='Correo'),
        ),
        migrations.AlterField(
            model_name='historicalusers',
            name='phone',
            field=models.IntegerField(blank=True, db_index=True, null=True, verbose_name='Telefono'),
        ),
        migrations.AlterField(
            model_name='users',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True, unique=True, verbose_name='Correo'),
        ),
        migrations.AlterField(
            model_name='users',
            name='phone',
            field=models.IntegerField(blank=True, null=True, unique=True, verbose_name='Telefono'),
        ),
    ]
