# Generated by Django 3.2.4 on 2021-09-15 13:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registers', '0004_auto_20210909_2036'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='stock',
            field=models.IntegerField(blank=True, default=1, null=True, verbose_name='Cantidad'),
        ),
    ]
