# Generated by Django 3.2.4 on 2021-08-07 04:27

from django.db import migrations, models
import registers.models


class Migration(migrations.Migration):

    dependencies = [
        ('registers', '0004_auto_20210806_2251'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicalusers',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True, verbose_name='Correo'),
        ),
        migrations.AlterField(
            model_name='historicalusers',
            name='image',
            field=models.TextField(blank=True, max_length=100, null=True, verbose_name='Imagen'),
        ),
        migrations.AlterField(
            model_name='historicalusers',
            name='phone',
            field=models.IntegerField(blank=True, null=True, verbose_name='Telefono'),
        ),
        migrations.AlterField(
            model_name='historicalusers',
            name='surnames',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='Apellidos'),
        ),
        migrations.AlterField(
            model_name='historicalusers',
            name='user_active',
            field=models.BooleanField(default=True, verbose_name='usuario activo'),
        ),
        migrations.AlterField(
            model_name='historicalusers',
            name='user_admin',
            field=models.BooleanField(default=False, verbose_name='usuario administrador'),
        ),
        migrations.AlterField(
            model_name='users',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True, verbose_name='Correo'),
        ),
        migrations.AlterField(
            model_name='users',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=registers.models.url_user, verbose_name='Imagen'),
        ),
        migrations.AlterField(
            model_name='users',
            name='phone',
            field=models.IntegerField(blank=True, null=True, verbose_name='Telefono'),
        ),
        migrations.AlterField(
            model_name='users',
            name='surnames',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='Apellidos'),
        ),
        migrations.AlterField(
            model_name='users',
            name='user_active',
            field=models.BooleanField(default=True, verbose_name='usuario activo'),
        ),
        migrations.AlterField(
            model_name='users',
            name='user_admin',
            field=models.BooleanField(default=False, verbose_name='usuario administrador'),
        ),
    ]
