# Generated by Django 3.2.4 on 2021-08-07 04:48

from django.db import migrations, models
import registers.models


class Migration(migrations.Migration):

    dependencies = [
        ('registers', '0005_auto_20210806_2327'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=registers.models.url_book, verbose_name='Imagen'),
        ),
        migrations.AlterField(
            model_name='order',
            name='deliver_date',
            field=models.DateTimeField(verbose_name='Fecha de Entrega'),
        ),
    ]
