# Generated by Django 3.2.4 on 2021-09-15 13:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registers', '0005_book_stock'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='borrowed',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='Prestados'),
        ),
    ]
