# Generated by Django 3.2.4 on 2021-09-16 18:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registers', '0006_book_borrowed'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalusers',
            name='active_order',
            field=models.BooleanField(blank=True, default=False, null=True, verbose_name='Pedido Activo'),
        ),
        migrations.AddField(
            model_name='users',
            name='active_order',
            field=models.BooleanField(blank=True, default=False, null=True, verbose_name='Pedido Activo'),
        ),
    ]
