# Generated by Django 3.2.4 on 2021-09-17 05:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registers', '0007_auto_20210916_1325'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='historicalusers',
            name='active_order',
        ),
        migrations.RemoveField(
            model_name='users',
            name='active_order',
        ),
        migrations.AlterField(
            model_name='historicalusers',
            name='phone',
            field=models.CharField(blank=True, db_index=True, max_length=10, null=True, verbose_name='Telefono'),
        ),
        migrations.AlterField(
            model_name='users',
            name='phone',
            field=models.CharField(blank=True, max_length=10, null=True, unique=True, verbose_name='Telefono'),
        ),
    ]
