# Generated by Django 3.2.4 on 2021-09-17 06:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registers', '0009_auto_20210917_0040'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicalusers',
            name='names',
            field=models.CharField(default='', max_length=150, verbose_name='Nombres'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='historicalusers',
            name='phone',
            field=models.CharField(db_index=True, default='', max_length=9, verbose_name='Telefono'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='historicalusers',
            name='surnames',
            field=models.CharField(default='', max_length=150, verbose_name='Apellidos'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='users',
            name='names',
            field=models.CharField(default='', max_length=150, verbose_name='Nombres'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='users',
            name='phone',
            field=models.CharField(default='', max_length=9, unique=True, verbose_name='Telefono'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='users',
            name='surnames',
            field=models.CharField(default='', max_length=150, verbose_name='Apellidos'),
            preserve_default=False,
        ),
    ]
