# Generated by Django 3.2.4 on 2021-09-17 06:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registers', '0010_auto_20210917_0112'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicalusers',
            name='names',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='Nombres'),
        ),
        migrations.AlterField(
            model_name='historicalusers',
            name='surnames',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='Apellidos'),
        ),
        migrations.AlterField(
            model_name='users',
            name='names',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='Nombres'),
        ),
        migrations.AlterField(
            model_name='users',
            name='surnames',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='Apellidos'),
        ),
    ]
