# Generated by Django 3.2.4 on 2021-09-17 15:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registers', '0012_auto_20210917_0117'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicalusers',
            name='phone',
            field=models.CharField(db_index=True, max_length=9, verbose_name='Telefono'),
        ),
        migrations.AlterField(
            model_name='users',
            name='phone',
            field=models.CharField(max_length=9, unique=True, verbose_name='Telefono'),
        ),
    ]
