# Generated by Django 3.2.4 on 2021-09-17 16:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registers', '0013_auto_20210917_1044'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicalusers',
            name='names',
            field=models.CharField(max_length=150, verbose_name='Nombres'),
        ),
        migrations.AlterField(
            model_name='historicalusers',
            name='surnames',
            field=models.CharField(max_length=150, verbose_name='Apellidos'),
        ),
        migrations.AlterField(
            model_name='users',
            name='names',
            field=models.CharField(max_length=150, verbose_name='Nombres'),
        ),
        migrations.AlterField(
            model_name='users',
            name='surnames',
            field=models.CharField(max_length=150, verbose_name='Apellidos'),
        ),
    ]
